version: '3'

services:
  django-server:
        image: django-server
        build: .
        environment:
            DB_NAME: django-postgres
            DB_USER: castel
            DB_PASSWORD: 1234
            DB_HOST: db
            DB_PORT: 5432
        ports:
            - 8000:8000